### ISSUE TITLE
Update Zendesk theme based on designs

### ISSUE THREAD

**Issue by briangrossman** [mitodl/mitxonline-zendesk-theme#3]
We have a design for the Zendesk support center. It can be found [here](https://projects.invisionapp.com/share/GN122PW0THWD#/screens/461521815) I've included a screenshot below. 

The support center in progress can be found here: https://mitxonline.zendesk.com/hc/en-us

Please update the theme to match the proposed design with a few notes

--------------------

**Proposed design**
![image](https://user-images.githubusercontent.com/21342568/145723867-8e181da4-6bee-4852-88eb-7d19e2097531.png)

--------------------

**Acceptance Criteria**
- [x] Match the designs to the [InVision mock up](https://projects.invisionapp.com/share/GN122PW0THWD#/screens/461521815)
- [x] `Submit a request` link (upper right) will open a page to submit a new support request ([xPRO example](https://xpro.zendesk.com/hc/en-us/requests/new))
- [ ] There are only two buttons. Use the design of the top row of buttons from Invision, but with two buttons rather than three: 
![image](https://user-images.githubusercontent.com/21342568/145723922-e2de3551-1c0f-4052-a750-d7147e8ea529.png)
- [x] The Invision design uses the wrong font. Use fonts that match the rest of the MITx Online site (primarily Montserrat)
- [x] The title of page should be `Support Center` rather than `Help & FAQs`
- [x] Add a `Can't find what you're looking for?` section, similar to xPRO. Just above the footer. 
   - [x] The horizontal rule should have a background-color of ![#C2C2C2](https://via.placeholder.com/15/c2c2c2/000000?text=+) `#c2c2c2`
   - [x] The section background-color should be ![#F5F5F5](https://via.placeholder.com/15/f5f5f5/000000?text=+) `#f5f5f5`
   - [x] Clicking `Contact Us` will open a page to submit a new support request ([xPRO example](https://xpro.zendesk.com/hc/en-us/requests/new)) 
![image](https://user-images.githubusercontent.com/21342568/145724389-32d14e85-e533-4315-ac4a-9620a012f6a8.png)

**Comment by arslanashraf7** [comment]
@briangrossman There are a few comments:

- The Support Center [link](https://mitxonline.zendesk.com/hc/en-us) mentioned in the ticket is restricted and we would need to make it publically accessible. (We probably need to make it public in case we need to access it, I tried with my Kerberos but wasn't successful as well)
- (Update) There is an open PR https://github.com/mitodl/mitxonline-zendesk-theme/pull/2 that should resolve most of the footer part.

**Comment by briangrossman** [comment]
> @briangrossman There are a few comments:
> 
> * The Support Center [link](https://mitxonline.zendesk.com/hc/en-us) mentioned in the ticket is restricted and we would need to make it publically accessible. (We probably need to make it public in case we need to access it, I tried with my Kerberos but wasn't successful as well)

I believe you are now set up as a Light Agent (your edly address) and should be able to view this. Let me know if you're not.


> * (Update) There is an open PR [style: match the theme footer with MITxOnline App #2](https://github.com/mitodl/mitxonline-zendesk-theme/pull/2) that should resolve most of the footer part.

Great. Yes... that PR should take care of the footer. 



> * Could you try and export the hero background behind search bar, which is added as bitmaps in the Invision, I tried but wasn't able to export that.

I was also unable to do so. I'll work on getting it for you.

**Comment by arslanashraf7** [comment]
@briangrossman Since this PR has been merged. You should be able to deploy the theme from `main` branch now. Let me know if you see any issues.

**Comment by briangrossman** [comment]
Closed when https://github.com/mitodl/mitxonline-zendesk-theme/pull/4 completed.
